rrt:
  ros__parameters:
    waypoints_path: "/f1tenth_ws/src/rrt/racelines/e7_floor5.csv" 
    odom_topic:  "/pf/pose/odom"
    segments: 512
    velocity_min: 0.5
    velocity_max: 2.0
    lookahead_distance: 3.0
