rrt:
  ros__parameters:
    waypoints_path: "/f1tenth_ws/src/rrt/racelines/e7_floor5.csv" 
    odom_topic:  "/pf/pose/odom"
    segments: 1024 # Number of points to interpolate to. The bigger the map, the more the number of segments
    velocity_min: 0.5
    velocity_max: 2.0
    cells_per_meter: 10
    lookahead_distance: 3.0
    is_sim: False
